export const FETCH_TRENDING_MOVIES = 'FETCH_TRENDINGS_MOVIES';
export const FETCH_POPULAR_MOVIES = 'FETCH_POPULAR_MOVIES';
export const FETCH_TOP_RATED_MOVIES = 'FETCH_TOP_RATED_MOVIES';
export const FETCH_UPCOMING_MOVIES = 'FETCH_UPCOMING_MOVIES';
export const FETCH_NOW_PLAYING = 'FETCH_NOW_PLAYING';
export const FETCH_MOVIE = 'FETCH_MOVIE';
export const FETCH_MOVIE_CREDITS = 'FETCH_MOVIE_CREDITS';
export const REMOVE_MOVIE = 'REMOVE_MOVIE';

export const FETCH_POPULAR_TV = 'FETCH_POPULAR_TV';
export const FETCH_TOP_RATED_TV = 'FETCH_TOP_RATED_TV';
export const FETCH_TV = 'FETCH_TV';
export const FETCH_TV_CREDITS = 'FETCH_TV_CREDITS';
export const REMOVE_TV = 'REMOVE_TV';

export const FETCH_PERSON = 'FETCH_PERSON';
export const FETCH_PERSON_CREDITS = 'FETCH_PERSON_CREDITS';
export const REMOVE_PERSON = 'REMOVE_PERSON';

export const SEARCH_QUERY = 'SEARCH_QUERY';
export const REMOVE_SEARCH_QUERY = 'REMOVE_SEARCH_QUERY';

export const ERROR_MESSAGE = 'ERROR_MESSAGE';
